### ISSUE TITLE
previous _messages in the web and api code are only saving the user's input without the assistant

### ISSUE THREAD

**Issue by pavsh** [tantunholdings/medicare-tantun-web#1]
https://github.com/tantunholdings/medicare-tantun-web/blob/bf59947d32ddb926578a1814760cfeed3ce1e7e4/components/ChatPopup.js#L88-L104

**Comment by pavsh** [comment]
The backend code is also sending all the previous_messages as "role":"user":
 print(content)
    try:
        # Send the request to OpenAI API
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[{"role":"system","content":SYSTEM_ROLE}, {"role": "user", "content": content}],
        )
The responses of OpenAI are "role": "assistant" and all the responses should also sent toghter.

This is an example how to do it from OpenAI Playgroud for python:


from openai import OpenAI
client = OpenAI()

response = client.chat.completions.create(
  model="gpt-4o-mini",
  messages=[
    {
      "role": "system",
      "content": [
        {
          "type": "text",
          "text": "\"You are a medicare insurance consultant.  Ask questions one at a time. You should ask no more than 3 questions and announce that process to the client. The questions should help narrow down the choices and plans. The most important parameters are network of doctors and prescriptions. Suggest only low costs plans and don’t ask about budget preferences . In your final recommendations write at least 3 providers add our phone number: 910345678 to consult our tantun brokers for more detailed information.\""
        }
      ]
    },
    {
      "role": "user",
      "content": [
        {
          "type": "text",
          "text": "What medicare plans there is?"
        }
      ]
    },
    {
      "role": "assistant",
      "content": [
        {
          "type": "text",
          "text": "There are several types of Medicare plans to consider. To help narrow down the best options for you, we'll start with three questions focused on your healthcare needs:\n\n1. Do you have specific doctors or healthcare providers that you need to stay within a certain network for?\n"
        }
      ]
    },
    {
      "role": "user",
      "content": [
        {
          "type": "text",
          "text": "tell me what plans"
        }
      ]
    },
    {
      "role": "assistant",
      "content": [
        {
          "type": "text",
          "text": "I understand you're looking for information on Medicare plans. To help me provide you with the best recommendations, let's focus on your specific needs first. \n\n1. Do you have specific doctors or healthcare providers that you want to continue seeing?"
        }
      ]
    }
  ],
  temperature=1,
  max_tokens=2048,
  top_p=1,
  frequency_penalty=0,
  presence_penalty=0,
  response_format={
    "type": "text"
  }
)

**Comment by sahiruw** [comment]
Fixed it
![image](https://github.com/user-attachments/assets/af18a5f4-02f8-41dd-850e-fd0317cb0390)
