### ISSUE TITLE
The chatgpt in the homepage is not on the first frame

### ISSUE THREAD

**Issue by pavsh** [tantunholdings/medicare-tantun-web#15]
The chatgpt in the homepage is not on the first frame and you need to scroll, it's should be visble as the page loads ![image](https://github.com/user-attachments/assets/2ccd44ef-50fb-4f62-b018-676822aab844)
 i mean this part should be visble 👍 
![image](https://github.com/user-attachments/assets/4fd90677-cd25-4819-b709-74285a5eb0f0)

**Comment by sahiruw** [comment]
This is an issue with the ui design. You can check by setting the layout in figma to your screensize

**Comment by sahiruw** [comment]
If you need I can swap the chat section with the section above it

**Comment by pavsh** [comment]
Can we resize the image or the buttons? Elderly people sometimes doesn't scroll so we need it to be on the first frame. You have any idea?

**Comment by sahiruw** [comment]
We can reduce the font sizes and image height, but this would cut off faces again and make the landing page look less appealing

**Comment by pavsh** [comment]
Ok, you right.
Can than add some blinking clickable arrow to make the visitor to understand that he can scroll for more? I saw it many websites.

**Comment by pavsh** [comment]
Like this example:

https://unused-css.com/blog/animated-down-arrow/

**Comment by sahiruw** [comment]
Check 0ae7b715b72a7dd266f48e4a69d8d4cf20852271

**Comment by pavsh** [comment]
Put the arrow at the bottom in the middle like i draw in this screenshot : 
![image](https://github.com/user-attachments/assets/996e0042-94b6-4afd-9182-e3b13b7d0c73)

**Comment by sahiruw** [comment]
Fixed @pavsh

**Comment by pavsh** [comment]
After one press the arrow is disappearing and only at the bottom appears again. it should blink while you still have a room to scroll down and vice versa

**Comment by sahiruw** [comment]
It will disappear when the chat is in the view

**Comment by pavsh** [comment]
why?

**Comment by pavsh** [comment]
work
