### ISSUE TITLE
the three buttons have no actions

### ISSUE THREAD

**Issue by pavsh** [tantunholdings/medicare-tantun-web#19]
![image](https://github.com/user-attachments/assets/72ba80fd-1b7e-466c-9f62-e1b96a2d1d9e)
The buttons actions are:
1. Speak to an advisor : just open the Tawk chat already with a message "Hi i need an advisory about Medicare"
2. Find Medicare plan : start a session with chatgpt.
3. the "free about Medicare plans" is my mistake -> should be "Free Medicare Enrollment" and the action is: on mobile-> call us and desktop -> just open the Tawk chat already with a message "Hi i want to enroll into a Medicare plan"

**Comment by sahiruw** [comment]
Tawk does not have an option to open the chat with a predefined message

https://community.tawk.to/t/post-message-to-vidget-by-api/3097

**Comment by pavsh** [comment]
So let's just make it call us on mobile or open the tawk to chat in the desktop

**Comment by sahiruw** [comment]
Fixed with 46977c2361da91d2dd7ad74c88f0333829cd2af8

**Comment by sahiruw** [comment]
@pavsh

**Comment by pavsh** [comment]
work
