### ISSUE TITLE
Chatgpt issues 

### ISSUE THREAD

**Issue by pavsh** [tantunholdings/medicare-tantun-web#20]
The text in the chatgpt line is missing "ask anything about Medicare"
![image](https://github.com/user-attachments/assets/d6c90f41-c7a9-48ab-bf20-c68eb92cabdb)
And change the title "How can we assist you today" into "Ask our Medicare AI Assistant' Just above the chatgpt

**Comment by sahiruw** [comment]
Done f1363bca8e0b289b27334b974a8a7256af1fcfd6
