### ISSUE TITLE
The woman face is cut off :)

### ISSUE THREAD

**Issue by pavsh** [tantunholdings/medicare-tantun-web#21]
![image](https://github.com/user-attachments/assets/cbb15ce9-5a52-4f71-87ce-3f7b51eb5bac)

**Comment by sahiruw** [comment]
Either the top or the bottom part of the image have to be cutoff in wide screens

**Comment by pavsh** [comment]
It's better to dee the faces. Let's try to cut the bottom

**Comment by sahiruw** [comment]
Check now

**Comment by pavsh** [comment]
work
