### ISSUE TITLE
The call now button have no action in desktop mode. 

### ISSUE THREAD

**Issue by pavsh** [tantunholdings/medicare-tantun-web#32]
![image](https://github.com/user-attachments/assets/55ff60d0-ef73-408e-8879-e32404c544bd)
Should be contact us in desktop mode

**Comment by sahiruw** [comment]
Fixed with 338ce1f4aa9eecefebbef4a1f2b3728c8e508ce8

**Comment by pavsh** [comment]
The text is still "call us.." and should changed to "contact us" in desktop as the action itself.

**Comment by sahiruw** [comment]
Fixed aa4d3ff1481a8fd0e01cca40aa08b9217b0e9e2e
