### ISSUE TITLE
The phone icon and number is missing in the mobile version

### ISSUE THREAD

**Issue by pavsh** [tantunholdings/medicare-tantun-web#35]
![image](https://github.com/user-attachments/assets/d3d4b3e6-0b8e-475f-9c3f-adaea2e43484)

**Comment by pavsh** [comment]
![image](https://github.com/user-attachments/assets/994fb612-2bf9-442e-958c-639380465f42)

**Comment by sahiruw** [comment]
Do you need that? because there's a call button below it

**Comment by sahiruw** [comment]
Fixed

**Comment by pavsh** [comment]
The phone should be on the header  and sticky like the header: 
![image](https://github.com/user-attachments/assets/f7daad1e-6529-4eb3-959e-01e1199340aa)

**Comment by sahiruw** [comment]
Done

**Comment by pavsh** [comment]
works
