### ISSUE TITLE
The Typing in Editing FAQs and Blog is not working properly

### ISSUE THREAD

**Issue by pavsh** [tantunholdings/medicare-tantun-web#45]
Two bugs:

1. the disclaimer is on top of the text editor: 
![image](https://github.com/user-attachments/assets/1a6a93fc-7867-4523-a07a-b50185d17828)
2. The Text Cursor is jumping to the end of the section while typing:

https://github.com/user-attachments/assets/0f46519d-9153-4d77-a0fb-2036958d1977

**Comment by sahiruw** [comment]
Please check

**Comment by pavsh** [comment]
Now when trying to edit a blog, the entire text of the blig is missing in the editing: 
![image](https://github.com/user-attachments/assets/e7f27adb-a83f-4eab-9d6e-34b162414e2d)

**Comment by sahiruw** [comment]
Check now

**Comment by pavsh** [comment]
Works ok, you can put into the pull request after fixing the other bug #
