### ISSUE TITLE
The blog page is still CSR

### ISSUE THREAD

**Issue by pavsh** [tantunholdings/medicare-tantun-web#5]
In comparison with the FAQ which is rendered in SSR the Blog main page.tsx is still CSR.

**Comment by sahiruw** [comment]
Fixed with 28f26712dc3500e5e56d4da6d3f0bfcb0aa2578a

Depends on
https://github.com/tantunholdings/medicare-tantun-api/pull/3

**Comment by pavsh** [comment]
work

**Comment by pavsh** [comment]
work
